# Generated by Django 2.0.1 on 2018-01-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredrca', '0003_auto_20180121_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, to='coredrca.Disciplina'),
        ),
    ]
